# Generated by Django 5.1.1 on 2024-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
