# Generated by Django 5.1.1 on 2024-10-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_rentalagreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='owner_digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
