# Generated by Django 5.1.1 on 2024-10-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_user_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='video',
        ),
    ]
