# Generated by Django 5.1.1 on 2024-10-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_propertyvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.property'),
        ),
    ]
