# Generated by Django 5.1.1 on 2024-10-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_propertyvideo_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyVideo',
        ),
    ]
