# Generated by Django 5.1.1 on 2024-10-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
