# Generated by Django 5.1.1 on 2024-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_message_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='terms_and_conditions',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
