# Generated by Django 5.1.1 on 2024-10-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_property_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='token_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='token_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='token_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
