# Generated by Django 5.1.1 on 2024-12-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_property_is_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_rented',
        ),
    ]
