# Generated by Django 5.1.1 on 2024-12-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_tokenpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpayment',
            name='billingaddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenpayment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tokenpayment',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tokenpayment',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
