# Generated by Django 5.1.1 on 2024-12-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_tokenpayment_billingaddress_tokenpayment_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenpayment',
            old_name='billingaddress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='tokenpayment',
            old_name='pincode',
            new_name='pin_code',
        ),
    ]
