# Generated by Django 5.1.1 on 2025-01-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_property_is_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_rented',
            field=models.BooleanField(default=True),
        ),
    ]
