# Generated by Django 5.1.1 on 2025-01-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_propertyrental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
