# Generated by Django 5.1.1 on 2025-01-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_videosession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoSession',
        ),
    ]
