# Generated by Django 5.1.1 on 2025-02-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_householditem_householditemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdItemWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='myapp.householditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_wishlists', to='myapp.user')),
            ],
        ),
    ]
